### ISSUE TITLE
Does not build anymore (gVisor API changes)

### ISSUE THREAD

**Issue by hegdenischay** [v-byte-cpu/wirez#18]
gVisor has changed its API, and the program doesn't build anymore:

```
ubuntu@server:~/wirez$ go build
package github.com/v-byte-cpu/wirez
        imports github.com/v-byte-cpu/wirez/command
        imports github.com/v-byte-cpu/wirez/pkg/connect
        imports gvisor.dev/gvisor/pkg/tcpip
        imports gvisor.dev/gvisor/pkg/atomicbitops
        imports gvisor.dev/gvisor/pkg/cpuid
        imports gvisor.dev/gvisor/pkg/state
        imports gvisor.dev/gvisor/pkg/state/wire
        imports gvisor.dev/gvisor/pkg/gohacks: build constraints exclude all Go files in /home/ubuntu/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20220816193615-632fd54acfb3/pkg/gohacks
```

Used go version: go version go1.22.0 linux/arm64

Attempting to fix it by upgrading gVisor also does not work:

```
ubuntu@server:~/wirez$ GO111MODULE=on go get gvisor.dev/gvisor@go
go: added gvisor.dev/gvisor v0.0.0-20240301005136-96d748d5c7c5
ubuntu@server:~/wirez$ go build
# github.com/v-byte-cpu/wirez/pkg/connect
pkg/connect/network_stack.go:96:47: cannot convert ipNet.IP (variable of type net.IP) to type tcpip.Address
pkg/connect/network_stack.go:96:76: cannot convert ipNet.Mask (variable of type net.IPMask) to type tcpip.AddressMask
pkg/connect/network_stack.go:148:57: too many arguments in call to gonet.NewUDPConn
        have (*stack.Stack, *waiter.Queue, tcpip.Endpoint)
        want (*waiter.Queue, tcpip.Endpoint)
```

**Comment by ghost18881** [comment]
@hegdenischay build using golang 1.20

**Comment by kovreee** [comment]
@ghost18881 I have downgraded go to 1.20.0, but whenever I run go build in the directory it now shows nothing and any wirez command doesn't work.

**Comment by ce7er2s** [comment]
@kovreee @hegdenischay consider building with go1.17 (works fine for me)
You can find standalone toolchains at https://go.dev/dl/

**Comment by hegdenischay** [comment]
Hi @kovreee and @ce7er2s thanks for the comments, but I've already fixed the issues in #19 
It's just not merged yet.
